import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "GNS"))
from train_drone_gns import load_checkpoint
import torch
import numpy as np

# Logarithm map for SO(3): rotation matrix -> rotation vector
def so3_log(R):
    tr = R[..., 0, 0] + R[..., 1, 1] + R[..., 2, 2]
    cos_theta = ((tr - 1.0) * 0.5).clamp(-1.0 + 1e-7, 1.0 - 1e-7)
    theta = torch.acos(cos_theta).unsqueeze(-1)                  # (..., 1)
    vee = torch.stack([
        R[..., 2, 1] - R[..., 1, 2],
        R[..., 0, 2] - R[..., 2, 0],
        R[..., 1, 0] - R[..., 0, 1],
    ], dim=-1) * 0.5
    small = theta < 1e-4
    sin_safe = torch.sin(theta).clamp_min(1e-12)
    factor = torch.where(small, 1.0 + theta ** 2 / 6.0, theta / sin_safe)
    return factor * vee

# Exponential map for SO(3): rotation vector -> rotation matrix (Rodrigues' formula)
def so3_exp(w):
    theta = w.norm(dim=-1, keepdim=True).unsqueeze(-1)          # (..., 1, 1)
    K = torch.zeros(w.shape[:-1] + (3, 3), dtype=w.dtype, device=w.device)
    K[..., 0, 1], K[..., 0, 2], K[..., 1, 2] = -w[..., 2], w[..., 1], -w[..., 0]
    K[..., 1, 0], K[..., 2, 0], K[..., 2, 1] = w[..., 2], -w[..., 1], w[..., 0]
    small = theta < 1e-4
    theta_safe = theta.clamp_min(1e-12)
    A = torch.where(small, 1.0 - theta ** 2 / 6.0, torch.sin(theta_safe) / theta_safe)
    B = torch.where(small, 0.5 - theta ** 2 / 24.0, (1.0 - torch.cos(theta_safe)) / theta_safe ** 2)
    eye = torch.eye(3, device=w.device, dtype=w.dtype).expand(K.shape)
    return eye + A * K + B * (K @ K)

def orthonormalize(R):
    U, _, Vt = np.linalg.svd(R)
    return U @ np.diag([1.0, 1.0, np.linalg.det(U @ Vt)]) @ Vt


class Drone_Dynamics:
    def __init__(self, model_path):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model, self.cfg, self.settings, _ = load_checkpoint(model_path, self.device)
        self.model.eval()
        self.h = self.model.h                      
        self.hist = None
        print("Model loaded successfully.")
        print(f"Model history length needed: {self.h}")


    def set_state_history(self, com_hist, R_hist):
        self.hist = [(np.asarray(c, float), np.asarray(R, float)) for c, R in zip(com_hist, R_hist)]
 

    def make_tensor(self, a):
        return torch.as_tensor(np.asarray(a), dtype=torch.float32, device=self.device).unsqueeze(0)
 

    def get_propulsion_force(self, rotor_speeds, R_curr):
        # Takes in the rotor speeds and the current rotation matrix to compute the propulsion force in the world frame.
        # Uses learned k_f and k_m coefficients to compute the thrust and yaw moment generated by the rotors.
        # (known physics: T = k_f w^2, yaw moment k_m w^2)
        f_thr, tau_thr = self.model.thrust_wrench(rotor_speeds, R_curr)
        return f_thr, tau_thr

    def get_aero_force(self, com_prev, com_curr, R_prev, R_curr, rotor_speeds, wind_vector, wall_normal_vector, wall_center_point):
        
        #Takes in the previous and current center of mass positions, previous and current rotation matrices,
        #rotor speeds, wind vector, wall normal vector, and wall center point it will then use this information
        #to generate the features for each of the nodes in the GNN's graph representation of the drone: 
        #For COM, arm, pad nodes [u, ||u||, node_type] for the rotor nodes [u, ||u||, rotor_speed, distance_to_wall, node_type]
        aero = self.model.aero_forces(com_prev, com_curr, R_prev, R_curr, rotor_speeds, wind_vector, wall_normal_vector, wall_center_point)
        f_aero, tau_aero = aero["F"], aero["tau"]
        return f_aero, tau_aero

    def get_non_contact_accel(self, f_thr, tau_thr, f_aero, tau_aero, R_prev, R_curr):
        mass, dt = float(self.model.mass), float(self.model.dt)
        g = torch.tensor([0.0, 0.0, -float(self.cfg.gravity)], device=self.device)
        
        F_thr_N, F_aero_N = self.model.to_newtons(f_thr)[0], self.model.to_newtons(f_aero)[0]        # N
        a_com = (F_thr_N + F_aero_N) / mass + g                                    # m/s^2
        
        tau_nc = tau_thr + tau_aero
        tau_N = self.model.to_newtons(tau_nc)[0]                                            # N m, thrust + aero
        

        
        
        
        R = R_curr[0]
        I_body = self.model.J_body * mass                                                   # kg m^2
        J_w = R @ I_body @ R.T                                                     # world-frame inertia
        w = so3_log(R @ R_prev[0].T) / dt                                          # rad/s, last step

        #Calculates the angular acceleration of the drone in the world frame
        alpha = torch.linalg.solve(J_w, tau_N - torch.linalg.cross(w, J_w @ w))    # rad/s^2
        
        #Gets the locations of all of the contact nodes in the world frame
        r = R @ self.model.contact_rest.T                                          # (3, N) lever arms
        r = r.T                                                                    # (N, 3), world frame

        #Computes the acceleration of each contact node in the world frame
        a_i = (a_com + torch.linalg.cross(alpha.expand_as(r), r)
                + torch.linalg.cross(w.expand_as(r), torch.linalg.cross(w.expand_as(r), r)))   # (N, 3)
        a_nc = (a_i * dt ** 2).unsqueeze(0)                                        # per-step units

        return a_nc

    def get_contact_forces(self, com_h, R_h, acceleration_before_contact, wall_normal_vector, Wall_center_position):
        #Takes the COM history and rotation history, and will ccompute a per node history
        #This will be used in the "contact_forces" function to calculate the finite difference velicity of the contact nodes.
        node_hist = [com.unsqueeze(1) + torch.einsum('bij,nj->bni', R, self.model.contact_rest) for com, R in zip(com_h, R_h)]
        
        #Takes in the node history, acceleration before contact, wall normal vector, and wall center position to compute contact forces.
        #Internally it will compute a per node feature consiting of [Vel_t,Vel_t-1, a_nc, a_nc * n, vel_t * n, dist_to_wall, wall_normal_vector, node type]
        #Outputs a per-node normal force and friction force
        phi_c, gate = self.model.contact_forces(node_hist, acceleration_before_contact, wall_normal_vector, Wall_center_position)               # (1, nodes, 3), gate
        F_nodes = self.model.to_newtons(phi_c)[0]                                          

        # Split each node's force into normal and friction components.
        F_normal_mag = F_nodes @ wall_normal_vector                                                
        F_normal = F_normal_mag[:, None] * wall_normal_vector                                     
        F_friction = F_nodes - F_normal                                          

        # Lever arms: each contact node relative to the COM, world frame.
        R = R_h[-1][0]                                                            
        r = (R @ self.model.contact_rest.T).T                                              

        # Sum into the net contact wrench on the drone.
        F_contact = (F_normal + F_friction).sum(dim=0)                            
        tau_contact = torch.linalg.cross(r, F_normal + F_friction, dim=-1).sum(dim=0)   

        return dict(F_normal=F_normal, F_friction=F_friction, 
                    F_contact=F_contact, tau_contact=tau_contact)

    def rigid_body_integrator_euler(self, F_total, tau_total, com_prev, com_curr, R_prev, R_curr):
        #Takes in the total force (N) and total moment about the COM (N m) acting on the drone, plus the
        #previous and current COM positions and rotation matrices, and propagates the pose one time step.
        #Simple version for the MPC: Verlet on the COM, and a plain (semi-implicit) Euler step on the
        #angular velocity using Euler's rotation equation. Gravity is added here, at the COM.
        mass, dt = float(self.model.mass), float(self.model.dt)
        g = torch.tensor([0.0, 0.0, -float(self.cfg.gravity)], device=self.device)
        I_body = self.model.J_body * mass                                                   # kg m^2
        c_prev, c_curr = com_prev[0], com_curr[0]
        R0, R1 = R_prev[0], R_curr[0]
 
        #Translation:  com_next = 2 com_curr - com_prev + (F/m + g) dt^2
        com_next = 2.0 * c_curr - c_prev + (F_total / mass + g) * dt ** 2
 
        #Angular velocity over the last step, from the last two attitudes
        w = so3_log(R1 @ R0.T) / dt                                                         # rad/s
 
        #Angular acceleration from Euler's rotation equation, in the world frame
        #  alpha = J_w^-1 (tau - w x J_w w),   J_w = R I R^T
        J_w = R1 @ I_body @ R1.T
        alpha = torch.linalg.solve(J_w, tau_total - torch.linalg.cross(w, J_w @ w))         # rad/s^2
 
        #Update the angular velocity, then rotate the current attitude by it
        w_next = w + alpha * dt
        R_next = so3_exp(w_next * dt) @ R1
        return com_next.unsqueeze(0), R_next.unsqueeze(0)




    @torch.no_grad()
    def step(self, rotor_speeds, wall_normal_vector, wall_center_point, wind_vector=(0.0, 0.0, 0.0)):
        #Takes in the rotor speeds (rad/s) for this step, the wall normal vector, a point on the wall, and the wind,
        #and uses the stored state history (set_state_history) to predict the next pose.
        #Runs the whole pipeline: propulsion -> aero GNN -> non-contact acceleration -> contact GNN -> integrator.
        #integrator="euler" uses the simple Euler rotation update (fine over MPC horizons); "momentum" uses the
        #angular-momentum-conserving update the model was trained with.
        #The stored history is updated with the new pose, so calling step() repeatedly rolls the drone forward.
 
        #Re-centers everything on the current COM (the same as in training). The model only depends on relative
        #positions, and float32 needs small numbers to resolve the per-step motion.
        anchor = self.hist[-1][0]
        com_h = [self.make_tensor(c - anchor) for c, _ in self.hist]
        R_h = [self.make_tensor(R) for _, R in self.hist]
        rotor_speeds = self.make_tensor(rotor_speeds)
        wind_vector = self.make_tensor(wind_vector)
        wall_normal_vector = self.make_tensor(wall_normal_vector)
        wall_center_point = self.make_tensor(np.asarray(wall_center_point) - anchor)
        com_prev, com_curr, R_prev, R_curr = com_h[-2], com_h[-1], R_h[-2], R_h[-1]
 
        #Thrust and yaw moment from the rotors (per-step units)
        f_thr, tau_thr = self.get_propulsion_force(rotor_speeds, R_curr)
 
        #Drag from the aero GNN, summed over the aero nodes (per-step units)
        f_aero, tau_aero = self.get_aero_force(com_prev, com_curr, R_prev, R_curr, rotor_speeds, wind_vector,
                                               wall_normal_vector, wall_center_point)
 
        #Acceleration every contact node would have with no contact (thrust + aero + gravity)
        a_nc = self.get_non_contact_accel(f_thr, tau_thr, f_aero, tau_aero, R_prev, R_curr)
 
        #Normal and friction force on every contact node from the contact GNN, and their net force and moment (N, N m)
        contact = self.get_contact_forces(com_h, R_h, a_nc, wall_normal_vector, wall_center_point)
 
        #Adds up every force and moment on the drone in Newtons (gravity is added inside the integrator)
        F_thr_N, tau_thr_N = self.model.to_newtons(f_thr)[0], self.model.to_newtons(tau_thr)[0]
        F_aero_N, tau_aero_N = self.model.to_newtons(f_aero)[0], self.model.to_newtons(tau_aero)[0]
        F_total = F_thr_N + F_aero_N + contact["F_contact"]
        tau_total = tau_thr_N + tau_aero_N + contact["tau_contact"]
 
        #Propagates the pose one step ("euler" for the MPC, "momentum" = the exact integrator used in training)
        com_next, R_next = self.rigid_body_integrator_euler(F_total, tau_total, com_prev, com_curr, R_prev, R_curr)
 
        #Back to world coordinates, and push the new pose onto the history
        com_next = com_next[0].double().cpu().numpy() + anchor
        R_next = orthonormalize(R_next[0].double().cpu().numpy())
        self.hist = self.hist[1:] + [(com_next, R_next)]
 
        return dict(com=com_next, R=R_next,
                    F_thrust=F_thr_N.cpu().numpy(), F_aero=F_aero_N.cpu().numpy(),
                    F_contact=contact["F_contact"].cpu().numpy(), tau_contact=contact["tau_contact"].cpu().numpy(),
                    F_normal=contact["F_normal"].cpu().numpy(), F_friction=contact["F_friction"].cpu().numpy())